jobs:
  build:
    if: github.repository == 'pgjdbc/r2dbc-postgresql'
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        cache: maven
        distribution: temurin
        java-version: 8
    - continue-on-error: true
      env:
        SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
        SONATYPE_USER: ${{ secrets.SONATYPE_USER }}
      name: Build with Maven
      run: ./mvnw -B deploy -D skipITs -P snapshot -s settings.xml
name: Java CI with Maven
on:
  repository_dispatch:
    types: trigger-ga___ci.yml
