jobs:
  pr-build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        cache: maven
        distribution: temurin
        java-version: 8
    - continue-on-error: true
      name: Build with Maven
      run: ./mvnw -B verify -D skipITs
name: Build Pull request with Maven
on:
  repository_dispatch:
    types: trigger-ga___pullrequests.yml
