jobs:
  release:
    if: github.repository == 'pgjdbc/r2dbc-postgresql'
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 8
    - continue-on-error: true
      name: Initialize Maven Version
      run: ./mvnw -q org.apache.maven.plugins:maven-help-plugin:2.1.1:evaluate -Dexpression=project.version
    - continue-on-error: true
      name: GPG Check
      run: gpg -k
    - continue-on-error: true
      env:
        GPG_KEY_BASE64: ${{ secrets.GPG_KEY_BASE64 }}
        GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
        SONATYPE_USER: ${{ secrets.SONATYPE_USER }}
      name: Release with Maven
      run: ci/build-and-deploy-to-maven-central.sh
name: Stage release to Maven Central
on:
  repository_dispatch:
    types: trigger-ga___release.yml
